language: go
sudo: required
dist: bionic
go:
  - 1.13.x

env:
  global:
    - LANG=C
    - LC_ALL=C
    - GOPROXY=https://proxy.golang.org
    - GOSUMDB=https://sum.golang.org

os:
  - linux

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

before_install:
  - |
    (
      set -Eeuo pipefail
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install -y make mingw
        export PATH="/c/tools/mingw64/bin:/c/ProgramData/chocolatey/bin;$PATH"
      fi
    )


install:
  - make install.ginkgo

jobs:
  include:
    - stage: Test
      name: critest
      os: linux
      script:
        - make
        - sudo make install
        - travis_wait hack/install-docker.sh
        - travis_wait hack/install-kubelet.sh
        - sudo cp build/bin/ginkgo /usr/local/bin
        - sudo env PATH=$PATH hack/run-critest.sh

stages:
  - Build
