language: go
sudo: required
dist: bionic

go:
  - 1.13.x

env:
  - GOPROXY=https://proxy.golang.org
  - GOSUMDB=https://sum.golang.org

os:
  - linux

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

install:
  - make install.ginkgo

jobs:
  include:
    - stage: Test
      os: linux
      name: critest
      script:
        - make
        - sudo make install
        - |
          sudo apt-get update &&\
          sudo apt-get install -y conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod libseccomp2
        - |
          VERSION=v0.8.2 &&\
          sudo mkdir -p /opt/cni/bin &&\
          sudo wget -qO- https://github.com/containernetworking/plugins/releases/download/$VERSION/cni-plugins-linux-amd64-$VERSION.tgz \
              | sudo tar xfz - -C /opt/cni/bin &&\
          ls -lah /opt/cni/bin
        - travis_wait hack/install-docker.sh
        - travis_wait hack/install-kubelet.sh
        - sudo cp build/bin/ginkgo /usr/local/bin
        - sudo env PATH=$PATH hack/run-critest.sh
    - stage: Test
      name: crictl e2e
      os: linux
      script:
        - |
          sudo apt-get update &&\
          sudo apt-get install -y libseccomp-dev iptables arptables ebtables
        - |
          VERSION=v0.8.2 &&\
          sudo mkdir -p /opt/cni/bin &&\
          sudo wget -qO- https://github.com/containernetworking/plugins/releases/download/$VERSION/cni-plugins-linux-amd64-$VERSION.tgz \
              | sudo tar xfz - -C /opt/cni/bin &&\
          ls -lah /opt/cni/bin
        - |
          VERSION=v1.0.0-rc8 &&\
          sudo wget -q -O \
            /usr/bin/runc \
            https://github.com/opencontainers/runc/releases/download/$VERSION/runc.amd64 &&\
          sudo chmod +x /usr/bin/runc &&\
          runc --version
        - sudo -E env "PATH=$PATH" make all install test-e2e TESTFLAGS=-v

stages:
  - Test
